version: '3'

services:
  web:
    build:
      context: .
    environment:
      - ARCADE_USERNAME=admin
      - ARCADE_PASSWORD=admin
    ports:
      - "6060:6060"
    volumes:
      - ./docs:/docs:rw
